models/products.py
from models import product_dbs

product_collection = product_dbs['products']


def get_products(category):
    try:
        products = product_collection.find(
            {"category": category}
        )

        return products
    except Exception as e:
        print(f"Error/get_products: {e}")
        return False


def get_product(product_id):
    try:
        product_info = product_collection.find_one(
            {"_id": product_id}
        )

        return product_info
    except Exception as e:
        print("Error/get_product: {e}")
        return False


def add_product(product_data):
    try:
        product_collection.insert_one(product_data)
        return True
    except Exception as e:
        print(f"Error/add_product: {e}")
        return False




controllers/auth_controller.py
from flask import Blueprint, render_template, request, make_response, redirect
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity

import models.user as user_dbs
import tools.utils as utils

auth = Blueprint('auth', __name__, template_folder="templates")


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        email = request.form.get('email')
        passwd = request.form.get('passwd')
        username = email.split('@')[0].strip()

        user_data = user_dbs.get_user_details(username)
        
        if user_data:
            # authenticate user
            if passwd == user_data['passwd']:
                # user auth success

                payload = {
                    "sub": username,
                    "iat": utils.current_epoch()
                }

                access_token = create_access_token(identity=payload)
                resp = make_response(redirect('/'))
                resp.set_cookie('access_token_cookie', access_token)

                print(f"{username} successfully logged-in")
                return resp
        print(f"{username} failed to login, password: {passwd}")
        return render_template('login.html', err="Incorrect Username/Password!")


@auth.route('/logout')
@jwt_required(locations='cookies')
def logout():
    user = get_jwt_identity()

    resp = make_response(redirect('/'))
    resp.set_cookie('access_token_cookie', '', expires=0)

    print(f"{user['sub']} has successfully logged out!")

    return resp


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        username = request.form.get('email').split('@')[0].strip()

        data = {
            "_id": username,
            "name": request.form.get('name'),
            "email": request.form.get('email'),
            "passwd": request.form.get('passwd'),
            "address": request.form.get('address'),
            "pincode": request.form.get('pincode'),
            "cart": {
                "cartid": utils.get_cart_id(),
                "total": 0,
                "items": {}
            },
            "previous_orders": []
        }

        if user_dbs.register(data):
            print(f"{username} have successfully registered!")
            return redirect('/auth/login')
        else:
            print(f"{username} couldn't register!")
            return render_template('login.html', err="You already have account with us, kindly login!")


controllers/cart_controller.py
from flask import Blueprint, render_template, redirect, url_for
from flask_jwt_extended import jwt_required, get_jwt_identity


import models.user as user_db
import models.products as product_db

cart = Blueprint('cart', __name__, template_folder="templates")


@cart.route('/')
@jwt_required(locations='cookies')
def view_cart():
    user = get_jwt_identity()

    user_data = user_db.get_user_details(user['sub'])
    user_cart = user_data['cart']

    cart = []

    for item in dict(user_cart['items']).keys():
        cart.append(dict(product_db.get_product(item)))
        cart[-1]['quantity'] = dict(user_cart)['items'][f'{item}']['quantity']

    return render_template('cart.html', cart=cart, total=user_cart['total'])


@cart.route('/checkout')
@jwt_required(locations='cookies')
def checkout_cart():
    user = get_jwt_identity()

    if (user_db.checkout_cart(user['sub'])):
        return redirect('/profile')
    else:
        return redirect('/')


@cart.route('/add/<productid>')
@jwt_required(locations='cookies')
def add_product(productid):
    user = get_jwt_identity()

    product_info = product_db.get_product(productid)

    if (user_db.add_to_cart(user['sub'], product_info['price'], productid)):
        return redirect(url_for('cart.view_cart'))
    else:
        return redirect('/')


@cart.route('/remove/<productid>')
@jwt_required(locations='cookies')
def remove_product(productid):
    user = get_jwt_identity()

    user_cart = user_db.get_user_details(user['sub'])['cart']
    quantity = dict(user_cart)['items'][f'{productid}']['quantity']
    product_info = product_db.get_product(productid)

    if (user_db.remove_from_cart(user['sub'], product_info['price'], productid, quantity)):
        return redirect(url_for('cart.view_cart'))
    else:
        return redirect('/')


@cart.route('/addquantity/<productid>')
@jwt_required(locations='cookies')
def add_quantity(productid):
    user = get_jwt_identity()

    product_info = product_db.get_product(productid)
    if (user_db.add_quantity(user['sub'], productid, product_info['price'])):
        return redirect(url_for('cart.view_cart'))
    else:
        return redirect('/')


@cart.route('/reducequantity/<productid>')
@jwt_required(locations='cookies')
def remove_quantity(productid):
    user = get_jwt_identity()

    product_info = product_db.get_product(productid)
    if (user_db.reduce_quantity(user['sub'], productid, product_info['price'])):
        return redirect(url_for('cart.view_cart'))
    else:
        return redirect('/')

controllers/category_controller.py
from flask import Blueprint, render_template


import models.products as product_db

category = Blueprint('category', __name__, template_folder="templates")


@category.route('/<categoryid>')
def category_home(categoryid):
    products = product_db.get_products(categoryid)
    return render_template('category.html', products=products, category=categoryid)

controllers/products_controller.py
from flask import Blueprint, render_template, request, redirect
from flask_jwt_extended import get_jwt_identity, jwt_required


import models.products as product_db
import tools.image as image_db


product =  Blueprint('product', __name__, template_folder="templates")


@product.route('/<productid>')
def product_info(productid):
    product = product_db.get_product(productid)
    return render_template('product.html', product=product)


@product.route('/add', methods=['GET', 'POST'])
@jwt_required(locations='cookies')
def add_product():
    user = get_jwt_identity()

    if user['sub'] != 'admin':
        return "UNAUTHORIZED", "403"

    if request.method == 'GET':
        return render_template('add_product.html')
    elif request.method == 'POST':
        img_file = request.files['img']

        name = request.form.get('name')
        short_desc = request.form.get('short_desc')
        description = request.form.get('description')
        category = request.form.get('category')
        price = request.form.get('price')
        img = image_db.upload(img_file, ''.join(name.lower().split()), 'Products')['secure_url']

        product_data = {
            "_id": ''.join(name.lower().split()),
            "name": name,
            "short_desc": short_desc,
            "desc": description,
            "category": category,
            "price": int(price),
            "img": img
        }

        if product_db.add_product(product_data):
            return redirect('/')
        else:
            print("Something went wrong!")
            return redirect('/')

templates/add_product.html
{%extends "base.html"%} {%block content%}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
  <div class="container">
    <div
      class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end"
    >
      <div class="col-first">
        <h1>Add Product</h1>
        <nav class="d-flex align-items-center">
          <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
          <a href="category.html">Product/add</a>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- End Banner Area -->

<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="login_box_img">
          <img class="img-fluid" src="/static/img/login.jpg" alt="" />
          <div class="hover">
            <h4>New to our website?</h4>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a class="primary-btn" href="{{ url_for('auth.register') }}"
              >Create an Account</a
            >
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="login_form_inner">
          <h3>Log in to enter</h3>
          <form
            class="row login_form"
            method="post"
            action="{{ url_for('product.add_product') }}"
            enctype="multipart/form-data"
            id="contactForm"
            novalidate="novalidate"
          >
            <div class="col-md-12 form-group">
              <input
                id="product-name"
                type="text"
                placeholder="Product Name"
                name="name"
                class="form-control"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Product Name'"
              />
            </div>
            <div class="col-md-12 form-group">
              <textarea
                class="form-control"
                id="product-description"
                placeholder="Product Description"
                name="short_desc"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Product Description'"
              ></textarea>
            </div>
            <div class="col-md-12 form-group">
              <textarea
              class="form-control"
              id="description"
              placeholder="Product Description"
              name="description"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Product Description'"
              ></textarea>
            </div>
            <div class="col-md-12 form-group">
              <input
              id="category"
              type="text"
              placeholder="Category"
              name="category"
                class="form-control"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Category'"
              />
            </div>
            <div class="col-md-12 form-group">
              <input
              id="product-price"
              type="number"
              name="price"
                class="form-control"
                placeholder="Price"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Price'"
              />
            </div>
            <div class="col-md-12 form-group">
              <input
              id="product-image"
              type="file"
              name="img"
              accept=".jpg,.jpeg,.png"
                class="form-control"
                placeholder="Product Image"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Product Image'"
              />
            </div>
            <div class="col-md-12 form-group">
              <button type="submit" value="submit" class="primary-btn">
                Add Product
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Login Box Area =================-->

{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='img/fav.png')}}"
    />
    <!-- Author Meta -->
    <meta name="author" content="CodePixar" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>Karma Shop</title>
    <!--
		CSS
		============================================= -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/linearicons.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/font-awesome.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/themify-icons.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/owl.carousel.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/nice-select.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/nouislider.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/ion.rangeSlider.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/ion.rangeSlider.skinFlat.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/magnific-popup.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css')}}"
    />
  </head>

  <body>
    <!-- Start Header Area -->
    <header class="header_area sticky-header">
      <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="/"
              ><img src="static/img/logo.png" alt=""
            /></a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}"
                    >Login</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.register') }}"
                    >Register</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('profile') }}"
                    >Profile</a
                  >
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                  <a href="{{ url_for('cart.view_cart') }}" class="cart"
                    ><span class="ti-bag"></span
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!-- End Header Area -->
    {% block content %} 
    {# Content here #} 
    {% endblock %}

    <!-- start footer Area -->
    <footer class="footer-area section_gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                eiusmod tempor incididunt ut labore dolore magna aliqua.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>Stay update with our latest</p>
              <div class="" id="mc_embed_signup">
                <form
                  target="_blank"
                  novalidate="true"
                  action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                  method="get"
                  class="form-inline"
                >
                  <div class="d-flex flex-row">
                    <input
                      class="form-control"
                      name="EMAIL"
                      placeholder="Enter Email"
                      onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Enter Email '"
                      required=""
                      type="email"
                    />

                    <button class="click-btn btn btn-default">
                      <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </button>
                    <div style="position: absolute; left: -5000px">
                      <input
                        name="b_36c4fd991d266f23781ded980_aefe40901a"
                        tabindex="-1"
                        value=""
                        type="text"
                      />
                    </div>

                    <!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Follow Us</h6>
              <p>Let us be social</p>
              <div class="footer-social d-flex align-items-center">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div
          class="footer-bottom d-flex justify-content-center align-items-center flex-wrap"
        >
          <p class="footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart-o" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    <script src="{{ url_for('static', filename='js/vendor/jquery-2.2.4.min.js')}}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/jquery.ajaxchimp.min.js')}}"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <script src="{{ url_for('static', filename='js/jquery.sticky.js')}}"></script>
    <script src="{{ url_for('static', filename='js/nouislider.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/countdown.js')}}"></script>
    <script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/owl.carousel.min.js')}}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{{ url_for('static', filename='js/gmaps.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

templates/cart.html
{%extends "base.html"%} {%block content%}

<!--================Cart Area =================-->
<section class="cart_area">
  <div class="container">
    <div class="cart_inner">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Product</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
            </tr>
          </thead>
          <tbody>
            {%for item in cart%}
            <tr>
              <td>
                <div class="media">
                  <div class="d-flex">
                    <img src="{{ item['img'] }}" alt="{{ item['name'] }}" />
                  </div>
                  <div class="media-body">
                    <p>{{ item['name'] }}</p>
                  </div>
                </div>
              </td>
              <td>
                <h5>{{ item['price'] }}</h5>
              </td>
              <td>
                <div class="input-group quantity mx-auto" style="width: 100px">
                  <p>Quantity: {{ item['quantity'] }}</p>
                  <a
                    href="{{ url_for('cart.add_quantity', productid=item['_id']) }}"
                    >+</a
                  >
                  <a
                    href="{{ url_for('cart.remove_quantity', productid=item['_id']) }}"
                    >-</a
                  >
                  <a
                    href="{{ url_for('cart.remove_product', productid=item['_id']) }}"
                    >Remove</a
                  >
                </div>
              </td>
            </tr>
            {%endfor%}
            <tr>
              <td></td>
              <td>
                <h5>Subtotal</h5>
              </td>
              <td>
                <h5>{{ total }}</h5>
              </td>
            </tr>

            <tr class="out_button_area">
              <td></td>
              <td></td>
              <td>
                <div class="checkout_btn_inner d-flex align-items-center">
                  {% if total != 0 %}
                  <a href="{{ url_for('cart.checkout_cart') }}"
                    ><button
                      type="button"
                      class="btn btn-block btn-primary my-3 py-3"
                    >
                      Checkout
                    </button></a
                  >
                  {% else %}
                  <a href="#"
                    ><button
                      type="button"
                      class="btn btn-block btn-primary my-3 py-3"
                    >
                      Checkout
                    </button></a
                  >
                  {% endif %}
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!--================End Cart Area =================-->

{%endblock%}

templates/login.html
{%extends "base.html"%} {%block content%}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
  <div class="container">
    <div
      class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end"
    >
      <div class="col-first">
        <h1>Login/Register</h1>
        <nav class="d-flex align-items-center">
          <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
          <a href="category.html">Login/Register</a>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- End Banner Area -->

<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="login_box_img">
          <img class="img-fluid" src="/static/img/login.jpg" alt="" />
          <div class="hover">
            <h4>New to our website?</h4>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a class="primary-btn" href="{{ url_for('auth.register') }}"
              >Create an Account</a
            >
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="login_form_inner">
          <h3>Log in to enter</h3>
          <form
            class="row login_form"
            action="{{ url_for('auth.login') }}"
            method="post"
            id="contactForm"
            novalidate="novalidate"
          >
            <div class="col-md-12 form-group">
              <input
              type="email"
              id="email"
              name="email"
                placeholder="Username"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Email'"
              />
            </div>
            <div class="col-md-12 form-group">
              <input
                class="form-control"
                type="password" id="password" name="passwd"
                placeholder="Password"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Password'"
              />
            </div>
            <div class="col-md-12 form-group">
              <button type="submit" value="submit" class="primary-btn">
                Log In
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Login Box Area =================-->

{%endblock%}

templates/register.html
{%extends "base.html"%} {%block content%}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
  <div class="container">
    <div
      class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end"
    >
      <div class="col-first">
        <h1>Login/Register</h1>
        <nav class="d-flex align-items-center">
          <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
          <a href="category.html">Login/Register</a>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- End Banner Area -->

<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="login_box_img">
          <img class="img-fluid" src="/static/img/login.jpg" alt="" />
          <div class="hover">
            <h4>New to our website?</h4>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a class="primary-btn" href="{{ url_for('auth.login') }}"
              >Create an Account</a
            >
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="login_form_inner">
          <h3>Log in to enter</h3>
          <form
            class="row login_form"
            action="{{ url_for('auth.register') }}" method="post"
            id="contactForm"
            novalidate="novalidate"
          >
            <div class="col-md-12 form-group">
              <input
              type="text"
              id="name"
              name="name"
              class="form-control"
                placeholder="Name"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Name'"
              />
            </div>
            <div class="col-md-12 form-group">
              <input
              type="email"
              id="email"
              name="email"
              class="form-control"
                placeholder="Email"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Email'"
              />
            </div>
            <div class="col-md-12 form-group">
                <input
                type="password" id="password" name="passwd"
                class="form-control"
                  placeholder="Password"
                  onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Password'"
                />
              </div>
              <div class="col-md-12 form-group">
                <input
                type="number" id="pincode" name="pincode"
                class="form-control"
                  placeholder="Pincode"
                  onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Pincode'"
                />
              </div>
              <div class="col-md-12 form-group">
                <input
                type="text" id="address" name="address"
                class="form-control"
                  placeholder="Address"
                  onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Address'"
                />
              </div>
            <div class="col-md-12 form-group">
              <button type="submit" value="submit" class="primary-btn">
                Register
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Login Box Area =================-->

{%endblock%}